create database grocery_store_management;

-- 1. Supplier Table
CREATE TABLE supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from supplier;
select * from categories;
select * from employees;
select * from order_details;
select * from orders;
select * from products;
select * from customers;

-- 1 How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM Orders;

-- 2 which customers have placed the highest number of orders?
SELECT 
    c.cust_id,
    c.cust_name AS customer_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_orders DESC;

-- 3 What is the total and average purchase value per customer? 
SELECT
    c.cust_id,
    c.cust_name AS customer_name,
    ROUND(SUM(od.total_price), 2) AS total_purchase_value,
    ROUND(AVG(od.total_price), 2) AS avg_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC;

-- 4 Who are the top 5 customers by total purchase amount?
SELECT
    c.cust_id,
    c.cust_name AS customer_name,
    ROUND(SUM(od.total_price), 2) AS total_purchase_amount
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_amount DESC
LIMIT 5;

-- SECTION 2: PRODUCT PERFORMANCE
-- 6 How many products exist in each category?
SELECT
    cat.cat_name AS category_name,
    COUNT(p.prod_id) AS product_count
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name
ORDER BY product_count DESC;

-- 7 What is the average price of products by category?

SELECT
    cat.cat_name AS category_name,
    ROUND(AVG(p.price), 2) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name
ORDER BY avg_price DESC;

-- 8 Which products have the highest total sales volume (by quantity)?
SELECT
    p.prod_id,
    p.prod_name AS product_name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_quantity_sold DESC;

-- 9 What is the total revenue generated by each product?
SELECT
    p.prod_id,
    p.prod_name AS product_name,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY total_revenue DESC;

-- 10 How do product sales vary by category and supplier?
SELECT
    cat.cat_name AS category_name,
    s.sup_name AS supplier_name,
    COUNT(DISTINCT p.prod_id) AS num_products,
    SUM(od.quantity) AS total_quantity_sold,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY cat.cat_name, s.sup_name
ORDER BY cat.cat_name, total_revenue DESC;

-- SECTION 3: SALES AND ORDER TRENDS
-- 11 How many orders have been placed in total?
SELECT COUNT(ord_id) AS total_orders
FROM orders;

-- 12 What is the average value per order?
SELECT
    ROUND(AVG(order_total), 2) AS avg_order_value
FROM (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_totals;

-- 13 On which dates were the most orders placed?
SELECT
    order_date,
    COUNT(ord_id) AS orders_on_date
FROM orders
GROUP BY order_date
ORDER BY orders_on_date DESC
LIMIT 10;

-- 14 Monthly trends in order volume and revenue
SELECT
    MONTH(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS month_num,
    MONTHNAME(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS month_name,
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS order_year,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY order_year, month_num, month_name
ORDER BY order_year, month_num;

-- 15  How do order patterns vary across weekdays and weekends?
SELECT
    CASE
        WHEN DAYOFWEEK(STR_TO_DATE(o.order_date, '%m/%d/%Y')) IN (1, 7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    DAYNAME(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS day_name,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    ROUND(SUM(od.total_price), 2) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type, day_name
ORDER BY day_type, total_orders DESC;

-- SECTION 4: SUPPLIER CONTRIBUTION
-- 16 How many suppliers are there in the database?
SELECT COUNT(sup_id) AS total_suppliers
FROM supplier;

-- 17 Which supplier provides the most products?
SELECT
    s.sup_id,
    s.sup_name AS supplier_name,
    COUNT(p.prod_id) AS num_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY num_products DESC;

-- 18 What is the average price of products from each supplier?
SELECT
    s.sup_id,
    s.sup_name AS supplier_name,
    ROUND(AVG(p.price), 2) AS avg_product_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_product_price DESC;

-- 19 Which suppliers contribute the most to total product sales (by revenue)?
SELECT
    s.sup_id,
    s.sup_name AS supplier_name,
    ROUND(SUM(od.total_price), 2) AS total_revenue,
    SUM(od.quantity) AS total_units_sold
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

 -- SECTION 5: EMPLOYEE PERFORMANCE
 -- 20  How many employees have processed orders?
 SELECT COUNT(DISTINCT emp_id) AS employees_with_orders
FROM orders;

-- 21  Which employees have handled the most orders?
SELECT
    e.emp_id,
    e.emp_name AS employee_name,
    COUNT(o.ord_id) AS total_orders_handled
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders_handled DESC;

-- 22 What is the total sales value processed by each employee?
SELECT
    e.emp_id,
    e.emp_name AS employee_name,
    ROUND(SUM(od.total_price), 2) AS total_sales_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales_value DESC;

-- 23 What is the average order value handled per employee?
SELECT
    e.emp_id,
    e.emp_name AS employee_name,
    ROUND(AVG(order_totals.order_total), 2) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) AS order_totals ON o.ord_id = order_totals.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;

-- SECTION 6: ORDER DETAILS DEEP DIVE
-- 25 What is the relationship between quantity ordered and total price?
SELECT
    quantity,
    COUNT(*) AS num_line_items,
    ROUND(AVG(each_price), 2) AS avg_unit_price,
    ROUND(AVG(total_price), 2) AS avg_total_price,
    ROUND(SUM(total_price), 2) AS sum_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- 26 What is the average quantity ordered per product?
SELECT
    p.prod_id,
    p.prod_name AS product_name,
    ROUND(AVG(od.quantity), 2) AS avg_quantity_per_order
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity_per_order DESC;


-- 27 How does the unit price vary across products and orders?
SELECT
    p.prod_id,
    p.prod_name AS product_name,
    p.price AS listed_price,
    ROUND(MIN(od.each_price), 2) AS min_order_unit_price,
    ROUND(MAX(od.each_price), 2) AS max_order_unit_price,
    ROUND(AVG(od.each_price), 2) AS avg_order_unit_price,
    ROUND(STDDEV(od.each_price), 2) AS stddev_unit_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name, p.price
ORDER BY stddev_unit_price DESC;




